### ISSUE TITLE
data

### ISSUE THREAD

**Issue by dadawdadD** [ualsg/Visual-soundscapes#1]
Hello, is the street view dataset you provided incomplete? It does not seem to contain as many samples as mentioned in the article.

**Comment by yuanllong** [comment]
Hello, there are 579 street view images in Singapore and 749 street view images in Shenzhen. Is this the number of data sets in the paper? Is the data set provided by the warehouse complete?

**Comment by zhaotianhong** [comment]
Thank you for your question. Yes, the training datasets we provided consist of 579 and 749 street view images for Singapore and Shenzhen, respectively, as mentioned in the paper. The features and [original images](https://figshare.com/s/2e7e23a20be112d828ea) of these datasets are already available within this project. However, the large-scale datasets used for inference (around 270,000 images for Singapore and 320,000 for Shenzhen) are not open-source.
